#!/bin/bash
#
# git-ignore -- A command to help with management of .gitignore files
#

usage() {
    echo "usage: git ignore [options]"
    echo "Options: TBD"
}

list() {
    $(git check-ignore -v ./*)
}

echo "that"
while getopts ":l:p::" opt; do
    case "${opt}" in
        -l | --list )
            list;
            shift ;;
        -h | --help )
            usage;
            shift ;;
        -n | --dry-run )
            DRY_RUN=true;
            shift ;;
        -- )
            shift;
            break ;;
        * )
            usage;
            break ;;
        \? ) list ;
             shift;;
    esac
done



